(function initPracticumHelperBridgeShared() {
  if (typeof BRIDGE_BUILD !== "string" || !BRIDGE_BUILD) {
    return;
  }

  globalThis.PracticumHelperBridgeShared = {
    bridgeVersion: BRIDGE_BUILD,
    MESSAGE_TYPES,
    EVENT_TYPES,
    markBridgeInitialized,
    createRequestId,
    parseJsonSafe,
    createBridgeEnvelope,
    hasMatchingBridgeEnvelope,
    createYonoteSourceDiagnostics,
    getYonoteNetworkCaptureRegistry,
    resetYonoteNetworkCaptureRegistry,
    shouldCaptureYonoteApiResponse,
    captureYonoteApiSnapshot,
    classifyYonotePayloadShape,
    collectYonotePayloadNodeTypeHints,
    scoreYonoteStructuredCandidate,
    pickBestYonoteStructuredCandidate,
    findProseMirrorDocRoot,
    findTypedBlockRoot,
    findYonoteContentRoot,
    findWikiContentRoot,
    extractYonoteSourceAst,
    extractWikiSourceAst,
    extractWikiInlineImageAssets,
    extractYonoteSourceAstFromStructuredPayload,
    extractSourceAstFromProseMirrorNode,
    extractSourceAstFromTypedBlock,
    extractInlineTextFromStructuredNode,
    isMeaningfulStructuredAst,
    compileSourceAstToMarkdown,
    buildYonoteStructuredPayload,
    buildWikiStructuredPayload,
    buildYonoteFallbackPayload,
    buildYonoteNativeExportPayload,
    buildYonoteSourceResult,
    decodeTextBytes,
    extractZipEntriesFromArrayBuffer,
    pickPrimaryMarkdownZipEntry,
    compileTheoryBlocks,
    getYonoteSlugFromPath,
    isTheoryPath,
    extractRootBlockIdFromUrl,
    extractTreeId,
    extractRootNested,
    extractCreatedBlockId,
    buildTheoryBlockPayload,
    isAuthFailure
  };
})();
